package com.autohero.bdd.enums;

public enum SortOptions {
    PUBLISHED_AT_DESC,
    OFFER_PRICE_AMOUNT_MINOR_UNITS_ASC,
    OFFER_PRICE_AMOUNT_MINOR_UNITS_DESC,
    MILEAGE_DISTANCE_ASC,
    MILEAGE_DISTANCE_DESC,
    MANUFACTURER_ASC,
    MANUFACTURER_DESC
}
